In [13]:
import pandas as pd # Подключаем библиотеку pandas для анализа данных
animals_data = {'Name':['Cat','Wolf','Tiger','Elephant'],
              'Species':['Carnivore','Carnivore','Carnivore','Herbivore'],
              'Weight':[4 , 60 , 180 , 600],
              'Count':[5 , 10 , 4 , 2]} # Словарь
columns = ['Name','Species','Weight','Count'] # Название колонок
df = pd.DataFrame(animals_data , columns = columns) # Создание датафрейма
df.to_csv('animals.csv', index=False) # Экспорт данных
N = 2
df

       Name    Species  Weight  Count
0       Cat  Carnivore       4      5
1      Wolf  Carnivore      60     10
2     Tiger  Carnivore     180      4
3  Elephant  Herbivore     600      2

In [14]:
# Вывод строк, начиная с последней
df.tail(N)

       Name    Species  Weight  Count
2     Tiger  Carnivore     180      4
3  Elephant  Herbivore     600      2

In [15]:
# Вывод строк, начиная с первой
df.head(N)

   Name    Species  Weight  Count
0   Cat  Carnivore       4      5
1  Wolf  Carnivore      60     10

In [16]:
# Статистика по числам
df.describe()

           Weight     Count
count    4.000000   4.00000
mean   211.000000   5.25000
std    269.525509   3.40343
min      4.000000   2.00000
25%     46.000000   3.50000
50%    120.000000   4.50000
75%    285.000000   6.25000
max    600.000000  10.00000

In [17]:
# Выбор столбца
df['Weight']

0      4
1     60
2    180
3    600
Name: Weight, dtype: int64

In [18]:
# Выбор строк
df[2:3]

    Name    Species  Weight  Count
2  Tiger  Carnivore     180      4

In [19]:
# Группировка и агрегация
df.groupby('Species').agg({'Weight': 'mean'})

               Weight
Species
Carnivore   81.333333
Herbivore  600.000000

In [20]:
# Убираем из словаря ноль (https://pythonpip.ru/pandas/pandas-fillna)
df.fillna(value = 0)
df.dropna(1)

<ipython-input-20-827b82224804>:3: FutureWarning: In a future version of pandas all arguments of DataFrame.dropna will be keyword-only.
  df.dropna(1)

       Name    Species  Weight  Count
0       Cat  Carnivore       4      5
1      Wolf  Carnivore      60     10
2     Tiger  Carnivore     180      4
3  Elephant  Herbivore     600      2

In [21]:
# Фильтрация столбца по условию
df[df['Species'] == 'Herbivore']

       Name    Species  Weight  Count
3  Elephant  Herbivore     600      2

In [22]:
# Переименнование столбца
df.rename(columns={'Name': 'Имя'})

        Имя    Species  Weight  Count
0       Cat  Carnivore       4      5
1      Wolf  Carnivore      60     10
2     Tiger  Carnivore     180      4
3  Elephant  Herbivore     600      2